[package]
name = "approx-eq-trait"
version = "0.1.2"
edition = "2024"
description = "A trait for floating-point equality."
repository = "https://github.com/tipsypastels/approx-eq-trait"
license = "MIT"
